# Generated by Django 2.0.1 on 2018-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('ci', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=30)),
                ('fecha_de_nacimento', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
    ]
