# Generated by Django 2.0.1 on 2018-01-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliando', '0002_auto_20180116_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ManyToManyField(to='afiliando.Carrera'),
        ),
    ]
